version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m unittest discover

artifacts:
  files:
    - '**/*'  # Include all files and directories in the root directory
  discard-paths: no  # Retain the directory structure in the zip file
