version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
      - pip install boto3
  build:
    commands:
      - echo "Zipping the Lambda function code..."
      - zip -r function.zip .
      - ls -lh function.zip
  post_build:
    commands:
      - echo "Deploying the Lambda function..."
      - python deploy_lambda.py my-lambda-function function.zip
artifacts:
  files:
    - function.zip
