version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m unittest discover     

artifacts:
  files:
    - 'lambda_function.py'
