version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m unittest discover
      # Create a zip file of all files in the 'my_lambda_folder' directory
      - zip -r lambda_function.zip my-lambda-function/

artifacts:
  files:
    - 'lambda_function.zip'
