version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt 

  build:
    commands:
      - python -m unittest discover 

  artifacts:
    files:
      - '**/*' 
    base-directory: dist 
    name: my-lambda-function 
    type: zip
    discard-paths: no
    packaging: zip
    path: output/
