version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade awscli
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket lambda-bucket-005 --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
