version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m unittest discover
      - mkdir -p dist # Create the 'dist' directory

  post_build:
    commands:
      - cp -r src dist/  # Copy only the 'src' directory to the 'dist' directory

artifacts:
  files:
    - 'lambda_function.py'
  base-directory: dist 
  name: my-lambda-function 
  type: zip
  discard-paths: no
  packaging: zip
  path: output/
