version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt  # Install dependencies

  build:
    commands:
      - python -m unittest discover  # Run unit tests
      - echo "Packaging Lambda function..."
      - zip -r function.zip .  # Package the entire directory into a ZIP file
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name deployment-lambda-function --zip-file fileb://function.zip  # Deploy to Lambda

artifacts:
  files:
    - function.zip  # Save the Lambda package as an artifact
  discard-paths: no  # Retain the directory structure in the zip file
