version: 0.2

phases:
  install:
    commands:
      - npm install 

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - zip -r function.zip . 

artifacts:
  files:
    - '**/*'
  base-directory: dist 
  name: my-lambda-function 
  type: zip
  discard-paths: no
  packaging: zip
  path: output/
