version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping the Lambda function code..."
      - zip -r function.zip .
  post_build:
    commands:
      - echo "Deploying the Lambda function..."
      - python deploy_lambda.py Lambda-POC-Task function.zip
artifacts:
  files:
    - function.zip
