version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r function.zip .
artifacts:
  files:
    - function.zip
