version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r function.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://function.zip
 
artifacts:
  files:
    - function.zip
