AWSTemplateFormatVersion: '2010-09-09'
Description: Update Lambda Function
 
Parameters:  
  ArtifactBucket:
    Type: String
    Description: S3 bucket containing the Lambda function code
  ArtifactObjectKey:
    Type: String
    Description: S3 key of the Lambda function code artifact
  LambdaRoleArn:
    Type: String
    Description: ARN of the existing IAM role for the Lambda function
 
Resources:
  LambdaFunctionUpdate:
    Type: AWS::Lambda::Function
    Properties:      
      Code: 
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ArtifactObjectKey
      Role: !Ref LambdaRoleArn
