AWSTemplateFormatVersion: '2010-09-09'
Description: Update Lambda Function
 
Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the existing Lambda function to update
  ArtifactBucket:
    Type: String
    Description: S3 bucket containing the Lambda function code
  ArtifactObjectKey:
    Type: String
    Description: S3 key of the Lambda function code artifact
  LambdaRoleArn:
    Type: String
    Description: ARN of the existing IAM role for the Lambda function
 
Resources:
  LambdaFunctionUpdate:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunctionName
      CodeSha256: ""
      S3Bucket: !Ref ArtifactBucket
      S3Key: !Ref ArtifactObjectKey
      Role: !Ref LambdaRoleArn
    UpdatePolicy:
      CodeUpdatePolicy:
        ApplyCodeUpdatesOnly: true
