AWSTemplateFormatVersion: '2010-09-09'
Description: Update Lambda Function

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the existing Lambda function to update
  ArtifactBucket:
    Type: String
    Description: S3 bucket containing the Lambda function code
  ArtifactObjectKey:
    Type: String
    Description: S3 key of the Lambda function code artifact

Resources:
  # Update the existing Lambda function with new code from S3
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Role: !Ref LambdaRoleArn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ArtifactObjectKey
      Handler: index.handler
      Runtime: nodejs14.x  # Adjust the runtime accordingly

  # Create a new version of the Lambda function
  LambdaFunctionUpdate:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunctionName

    UpdatePolicy:
      CodeUpdatePolicy:
        ApplyCodeUpdatesOnly: true
